notifications:
  email: false

language: go

script:
  - make test

os:
  - linux
  - osx

install:
  - go get -u github.com/kardianos/govendor
  - go get -u github.com/jteeuwen/go-bindata/...
  - govendor install
